name: Continuous Integration and Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  sample-dotnet:
    runs-on: linux-apache
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: dotnet info
        run: sudo dotnet --info

      - name: restore 
        run: dotnet restore

      - name: build 
        run: dotnet build -c Release --no-restore

      - name: publish 
        run: dotnet publish -o /var/www/publish

      - name: copy publish to application
        run: sudo cp -r /var/www/publish/* /var/www/deploy-publish

      - name: restart nginx service
        run: sudo systemctl restart sample.service